---
apiVersion: getambassador.io/v3
kind: Mapping
metadata: 
  name: cartmapping
spec:     
  prefix: /cart/
  rewrite: /cart
  service: cartservice:7070
---
apiVersion: getambassador.io/v3
kind: Mapping
metadata: 
  name: admapping
spec:     
  prefix: /ad/
  rewrite: /ad
  service: adservice:9555
---
apiVersion: getambassador.io/v3
kind: Mapping
metadata: 
  name: reccomendationmapping
spec:     
  prefix: /reccomendation/
  rewrite: /reccomendation
  service: recommendationservice:8080