---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata: 
  name: frontend
spec:     
  prefix: /
  # host: "*"
  # rewrite: /
  service: frontend:80
  bypass_auth: false
