---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "jwt-filter"
  namespace: default
spec:
  JWT:
    jwksURI: "https://getambassador-demo.auth0.com/.well-known/jwks.json"
    validAlgorithms:
      - "none"
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: "example-filter-policy"
  namespace: default
spec:
  rules:
  - host: "*"
    path: /*
    filters:
    - name: jwt-filter
