FROM envoyproxy/envoy-dev:latest

#RUN apk update && apk add python3 bash curl
RUN apt update && apt install -y python3 bash gcc python3-pip gdb vim tmux htop net-tools curl
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD ./service.py /code
# ADD our stuff
ADD library.c /code
RUN gcc -shared -fPIC -g -o /code/library.so /code/library.c


ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
